version: v1.0.0
id: "ac.io/spec/common/principles"
type: "prompt"
name: "编程基本原则"
labels: ["principle"]
content:
  principles:
    - name: KISS
      description: 保持代码尽可能简单，避免不必要的复杂度
      examples:
        - 拆解复杂函数为小函数
        - 不引入过早优化

    - name: DRY
      description: 避免重复代码，提高可维护性
      examples:
        - 提取公共逻辑为函数或模块

    - name: YAGNI
      description: 不实现当前不需要的功能，避免浪费资源
      examples:
        - 不要为了“将来可能需要”而增加功能

    - name: Separation of Concerns
      description: 单一职责，每个模块只做一件事
      examples:
        - 将 UI 与业务逻辑分离
        - 将数据处理从视图中剥离
