version: v1.0.0
id: "ac.io/ctx/cursor/default"
type: "context"
name: "Cursor 基础规则"
labels: [cursor", "rules"]
summary: "Cursor 项目通用基础配置"
files:
  - path: ".cursor/principles.mdc"
    content: |
      ---
      alwaysApply: true
      ---

      # 编写任意代码都需严格遵循以下原则

      ```yaml
      {ac.io/spec/common/principles}
      ```
  - path: ".cursor/shell.mdc"
    content: |
      ---
      description: Shell脚本编写规范
      globs:
        - "**/*.sh"
      alwaysApply: false
      ---

      # 编写任意 shell 代码都需严格遵循以下原则

      ```yaml
      {ac.io/spec/lang/shell}
      ```
